version: "3.9"
services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
    mongo:
        image: "mongo:4.4"
        ports:
            - "27017:27017"
    gateway:
        build: "./gateway"
        image: "gateway:latest"
        ports:
            - "3000:3000"
        environment:
            - "REDIS_PORT=6379"
    web:
        build: "./web_server"
        image: "web:latest"
        ports:
            - "8080:8080"
